language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
#cache: cargo
before_script:
  - cargo install --force cargo-when
  - cargo install --force cargo-audit
script:
  # Tests should run on all supported rustc versions
  - cargo test --tests --examples
  - cargo test --doc
  - cargo test
  - cargo audit
notifications:
  email:
    on_success: never
